### ISSUE TITLE
Mysterious Trader ignores config

### ISSUE THREAD

**Issue by Lurrae** [Pbone3/PboneUtils#43]
Even when I have the Mysterious Trader's config setting disabled, the Mysterious Trader still seems to be able to spawn. Not only that, but he seems to enjoy constantly spawning and immediately despawning repeatedly throughout the night, spamming my chat with "[name] the Mysterious Trader has arrived! [name] the Mysterious Trader has departed!"
![image](https://user-images.githubusercontent.com/69269327/185263471-897a001b-b4b4-465c-b863-415b0152f659.png)

It's possible that this is some sort of mod conflict since I am playing with a bunch of other mods, but I've never run into this issue before with a similar modpack so I can't say for certain.

EDIT: The issue does seem to be a mod conflict- specifically with "Quality of Life". That mod has a config to make town NPCs spawn instantly once their bestiary entry is filled, and that config seems to be trying to force the Mysterious Trader to stay. I'll close this issue since it wasn't actually a problem with this mod. Sorry for the confusion!

**Comment by Rijam** [comment]
What you reported is perfectly valid. A lot of the stuff in the current version of the mod is broken. I have fixed many bugs in the upcoming update, but pbone hasn't uploaded it to the workshop yet.

Things that will be fixed in the next update (1.2.16)
- Fixed Miner and Mysterious Trader being loaded when the configs for them were turned off.
- Fixed the Item Toggles configs not working.
- Fixed the Princess' Happiness dialog when talking about the Miner or Mysterious Trader.
- Fixed infinite bait items being consumed.
- Obsidian sold by the Miner now costs 5 silver instead of no value.
- Corrected the tooltip on the Miner's Emblem saying 25% speed when it was actually 15% (Creator's Emblem is still 25%).
- Fixed the Buff Brazier not giving the Star in a Bottle and Sunflower buff.
- Fixed the Preparation Station not giving the Sharpening Station buff correctly.
- Added a sound when using the Preparation Station.
- Fixed Greedy Chest not working.
- Adjusted the items in the Mysterious Trader's shop. Now sells more items. Sells X in a Bottle accessories instead of X in a Balloon accessories. Sells the Terragrim instead of the Arkhalis.
- Mysterious Trader will sell 2 more items in Hardmode and 1 more item in Expert Mode.
- Corrupticlover can now be crafted with Red Solution.
- The Master Plan will no longer place or absorb liquids while the menu is open (Previously, clicking the menu buttons would place/absorb liquid).
- Moved Mod.Recipes to ModSystems.Recipes
- Fixed Chinese localization (Thanks Lin-cat)
